#!/bin/bash

set -x

docker exec -it hot curl  -H 'Content-Type: application/json' \
 --data "{\"type\":\"s3\",\"settings\":{\"bucket\":\"test\",\"endpoint\":\"$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' minio):9000\",\"protocol\":\"http\"}}" \
  -XPUT http://hot:9200/_snapshot/my_minio_repository

docker exec -it hot curl  -H 'Content-Type: application/json' \
  --data-binary @/usr/share/elasticsearch/config/docker_host/cluster.settings \
  -XPUT http://hot:9200/_cluster/settings

docker exec -it hot curl  -H 'Content-Type: application/json' \
  --data-binary @/usr/share/elasticsearch/config/docker_host/ilm.policy \
  -XPUT http://hot:9200/_ilm/policy/hot-warm-cold

docker exec -it hot curl  -H 'Content-Type: application/json' \
 --data-binary @/usr/share/elasticsearch/config/docker_host/ilm_hot-delete.policy \
  -XPUT http://hot:9200/_ilm/policy/hot-delete

docker exec -it hot curl  -H 'Content-Type: application/json' \
 --data-binary @/usr/share/elasticsearch/config/docker_host/index.template \
  -XPUT http://hot:9200/_index_template/test_indexes
