version: '3'
services:
  elasticsearch-hot:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: hot
    command: ["sh", "-c", "/usr/share/elasticsearch/bin/elasticsearch-plugin install repository-s3 -s --batch && /usr/local/bin/docker-entrypoint.sh"]
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      # - ELASTIC_PASSWORD=foobar
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - $PWD/hot/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml  
      - $PWD/hot/elasticsearch.keystore:/usr/share/elasticsearch/config/elasticsearch.keystore  
      - $PWD:/usr/share/elasticsearch/config/docker_host
    networks:
      - esnet

  elasticsearch-warm:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: warm
    command: ["sh", "-c", "/usr/share/elasticsearch/bin/elasticsearch-plugin install repository-s3 -s --batch && /usr/local/bin/docker-entrypoint.sh"]
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      # - ELASTIC_PASSWORD=foobar
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9201:9201
    volumes:
      - $PWD/warm/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml  
      - $PWD/warm/elasticsearch.keystore:/usr/share/elasticsearch/config/elasticsearch.keystore  
      - $PWD:/usr/share/elasticsearch/config/docker_host
    networks:
      - esnet

  elasticsearch-cold:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: cold
    command: ["sh", "-c", "/usr/share/elasticsearch/bin/elasticsearch-plugin install repository-s3 -s --batch && /usr/local/bin/docker-entrypoint.sh"]
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9202:9202
    volumes:
      - $PWD/cold/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml  
      - $PWD/cold/elasticsearch.keystore:/usr/share/elasticsearch/config/elasticsearch.keystore  
      - $PWD:/usr/share/elasticsearch/config/docker_host
    networks:
      - esnet
 
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    container_name: kibana
    ports:
      - "5601:5601"
    networks:
      - esnet
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml      
    depends_on:
      - elasticsearch-hot


  minio:
    image: minio/minio
    container_name: minio 
    command: server /data --console-address ":9001"
    environment:
      - "MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE"
      - "MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - /data:/home/jakelandis/workspace/data/minio
    networks:
      - esnet

networks:
  esnet:
